### ISSUE TITLE
Deselect item

### ISSUE THREAD

**Issue by paparent** [syropian/vue-multiclick#3]
Hi ! 

I don't know if it's intended that way but, would be great when clicking on a selected item, it deselect it. If it's not intended that way, maybe a props to enable that feature ? I'm willing to implement it, just wanted to know your thoughts beforehand :)

**Comment by syropian** [comment]
Hm, this library aims to replicate native OS filesystem selection, and I don't think any have toggling.

To get around it you can just do something like:

```html
<li @click="itemIsSelected(item) ? removeFromSelection(item) : itemClicked(item, $event)">
  ...
</li>
```

**Comment by paparent** [comment]
@syropian Thanks ! I'll implement it manually, it makes sense :)
