### ISSUE TITLE
Single item or max

### ISSUE THREAD

**Issue by paparent** [syropian/vue-multiclick#4]
Hi ! 

I know the component is named vue-multiclick... but it would be interesting to disable multiselection, while keeping to logic for selected items.. and/or maybe have to possibility of selecting a maximum of item? It's sure that with a maximum of items and the Shift key, it might be a little weird..

Any thoughts?

**Comment by syropian** [comment]
The problem is, disabling/limiting selection doesn't really make sense as a core feature of the library, but should be achievable by simply implementing methods or computed properties on the component vue-multiclick wraps.
